/// Action returned by [`Parser::feed`]: emit the byte as content or skip it.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Action {
    /// Byte is content — emit it.
    Emit = 0,
    /// Byte is part of an escape sequence — skip it.
    Skip = 1,
}

/// ECMA-48 parser states.
///
/// 15 variants covering CSI, OSC, DCS, APC/PM/SOS (collapsed),
/// SS2, SS3, Fe, and intermediate bytes. SOS/PM/APC share
/// `StringPassthrough` since their behavior is identical.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum State {
    Ground = 0,
    EscapeStart,
    CsiParam,
    CsiIntermediate,
    OscString,
    OscStEsc,
    DcsEntry,
    DcsParam,
    DcsPassthrough,
    DcsStEsc,
    /// SOS, PM, APC collapsed — all consume until ST.
    StringPassthrough,
    StringStEsc,
    Ss2,
    Ss3,
    EscIntermediate,
}

/// Minimal ECMA-48 state machine for classifying bytes as
/// escape-sequence or content. Does not interpret sequences.
///
/// Size: 1 byte (state stored as `u8` repr for branchless table decode).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct Parser {
    /// State stored as repr(u8) value directly, avoiding the
    /// STATE_FROM_INDEX indirection in the hot path.
    state_byte: u8,
}

// Compile-time assertions: Send + Sync.
const _: () = {
    const fn assert_send<T: Send>() {}
    const fn assert_sync<T: Sync>() {}
    assert_send::<Parser>();
    assert_sync::<Parser>();
};

impl Parser {
    /// Create a new parser in the ground state.
    #[inline]
    #[must_use]
    pub const fn new() -> Self {
        Self { state_byte: 0 } // Ground = 0
    }

    /// Reset the parser to the ground state.
    #[inline]
    pub fn reset(&mut self) {
        self.state_byte = 0;
    }

    /// Returns `true` if the parser is in the ground state.
    #[inline]
    #[must_use]
    pub const fn is_ground(&self) -> bool {
        self.state_byte == 0
    }

    /// Returns `true` if the parser is in a passthrough body state
    /// (OSC string, DCS passthrough, or SOS/PM/APC string).
    ///
    /// These states consume arbitrary-length body bytes until a
    /// terminator. Callers can use `memchr` to skip directly to
    /// the terminator instead of feeding each byte individually.
    ///
    /// Branchless: single shift + AND + compare. No conditional
    /// branches — avoids branch predictor pollution in tight loops.
    #[inline]
    #[must_use]
    pub const fn is_passthrough(&self) -> bool {
        // OscString=4, DcsPassthrough=8, StringPassthrough=10
        // Mask has exactly bits 4, 8, 10 set.
        const MASK: u16 = (1 << 4) | (1 << 8) | (1 << 10); // 0x0510
        // state_byte is always 0..=14, so the shift is safe for u16.
        MASK & (1u16 << (self.state_byte as u16)) != 0
    }

    /// Returns the current parser state.
    #[inline]
    #[must_use]
    pub fn state(&self) -> State {
        STATE_FROM_INDEX[self.state_byte as usize]
    }

    /// Feed a single byte through the state machine.
    ///
    /// Returns [`Action::Emit`] if the byte is content,
    /// [`Action::Skip`] if it is part of an escape sequence.
    ///
    /// Ground state (the common case) is handled inline.
    /// All other states use a precomputed 15×256 lookup table
    /// (3840 bytes, fits in L1) for branchless transitions.
    #[inline]
    pub fn feed(&mut self, byte: u8) -> Action {
        // Fast path: ground state (~80%+ of bytes).
        if self.state_byte == 0 {
            if byte == 0x1B {
                self.state_byte = 1; // EscapeStart
                return Action::Skip;
            }
            return Action::Emit;
        }
        // Table entry encoding: bits [4:1] = state repr, bit [0] = action.
        // state repr == index into STATE_FROM_INDEX == State as u8.
        let entry = STATE_TABLE[self.state_byte as usize][byte as usize];
        self.state_byte = (entry >> 1) & 0x0F;
        if entry & 1 == 0 {
            Action::Emit
        } else {
            Action::Skip
        }
    }
}

impl Default for Parser {
    fn default() -> Self {
        Self::new()
    }
}

// Include the precomputed state transition table.
// Generated by: python3 (see table generation in project history).
// Entry encoding: bits [4:1] = next_state, bit [0] = action (0=Emit, 1=Skip).
// 15 states × 256 bytes = 3840 bytes. Fits in L1 cache.
include!("state_table.rs");

/// Maps table index back to State enum — avoids unsafe transmute.
#[rustfmt::skip]
static STATE_FROM_INDEX: [State; 15] = [
    State::Ground, State::EscapeStart, State::CsiParam, State::CsiIntermediate,
    State::OscString, State::OscStEsc, State::DcsEntry, State::DcsParam,
    State::DcsPassthrough, State::DcsStEsc, State::StringPassthrough,
    State::StringStEsc, State::Ss2, State::Ss3, State::EscIntermediate,
];
